version: 0.2

env:
  parameter-store:
    TOKEN: /dev/tests/pipelinetoken

phases:
  pre_build:
    commands:
      - echo "TOKEN FOR THE PIPELINE IS:"
      - echo $TOKEN
  build:
    commands:
      - mkdir -p "artifacts"
      - cp "cloudformation/simple-s3-cf.yml" "artifacts/simple-s3-cf.yml"
      - cp "cloudformation/simple-s3-configuration.json" "artifacts/simple-s3-configuration.json"
      - cat "artifacts/simple-s3-configuration.yml"

artifacts:
  files:
    - "artifacts/simple-s3-cf.yml"
    - "artifacts/simple-s3-configuration.json"
