version: 0.2

env:
  parameter-store:
    TOKEN: /tests/simple-s3-pipeline/token
    ENVIRONMENT: /tests/simple-s3-pipeline/environment

phases:
  pre_build:
    commands:
      - echo "TOKEN FOR THE PIPELINE IS:"
      - echo $TOKEN
      - echo "ENVIRONMENT FOR THE PIPELINE IS:"
      - echo $ENVIRONMENT
  build:
    commands:
      - mkdir -p "artifacts"
      - cp "cloudformation/simple-s3-cf.yml" "artifacts/simple-s3-cf.yml"
      - cat "cloudformation/simple-s3-configuration.json"
      - sed -e "s/\${ENVIRONMENT}/$ENVIRONMENT/g;s/\${TOKEN}/$TOKEN/g" "cloudformation/simple-s3-configuration.json" > "artifacts/simple-s3-configuration.json"
      - cat "artifacts/simple-s3-configuration.json"

artifacts:
  files:
    - "artifacts/simple-s3-cf.yml"
    - "artifacts/simple-s3-configuration.json"
