AWSTemplateFormatVersion: 2010-09-09
Description: Deploys a super-simple S3 bucket from set of given parameters.

Parameters:
  AppName:
    Description: Name of the Application.
    Type: String
    Default: sample-santi-simple-app
  Environment:
    Description: Environment for the deployment (development, production)
    Type: String
    Default: dev
    AllowedValues:
      - development
      - production
    ConstraintDescription: Must be a valid environment.
  BucketName:
    Description: Name for the S3 bucket.
    Type: String
    Default: default-bucket-sample-santi
  VersioningConfiguration:
    Description: Describes the versioning state of an Amazon S3 bucket.
    Type: String
    Default: Suspended
    AllowedValues:
      - Suspended
      - Enabled

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Join ["-", [!Ref BucketName, !Ref Environment]]
      VersioningConfiguration:
        Status: !Ref VersioningConfiguration
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref BucketName, !Ref Environment]]
        - Key: Environment
          Value: !Ref Environment

Outputs:
  Environment:
    Description: Environment of the deployment
    Value: !Ref Environment
  BucketName:
    Description: S3 bucket name
    Value: !Ref MyBucket
  BucketArn:
    Description: S3 bucket arn
    Value: !GetAtt MyBucket.Arn
